spring:
  application:
    name: ${APP_NAME:dubbo-consumer-sidecar}
server:
  port: ${SERVER_PORT:5678}
sidecar:
  port: ${SIDECAR_PORT:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
zuul:
  routes:
    all:
      path: /**
      url: ${ZUUL_URL:http://localhost:8081}
